global:
  scrape_interval:     15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090

  - job_name: 'pve'
    static_configs:
      - targets:
        - ${PVE_HOST_IP}
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221

  - job_name: 'caddy'
    static_configs:
      - targets:
        - ${CADDY_HOST_IP}
    metrics_path: /metrics
